### ISSUE TITLE
Feature request: showing analyzer/refactor id in options page

### ISSUE THREAD

**Issue by huoyaoyuan** [JosefPihrt/RoslynTools#13]
So that I can find one quickly by id.

**Comment by JosefPihrt** [comment]
Hi, could you be more specific on your request? What is meant by "id"?

Options page contains only refactorings, not analyzers.

**Comment by huoyaoyuan** [comment]
That's something like `RCS1001`.
Some of them are part of "coding style", and sometimes conflict to my own preference. For example, `RCS1025 - Format each enum member on separate line`, but my rule is: place the whole enum definition on a single line, if there are only several members and no xml document.
I know I can suppress them in code or a ruleset, but I want to set a default warning level for all my projects. Does Roslyn allows to do this?

**Comment by JosefPihrt** [comment]
I use ruleset to enable/disable analyzers or to change severity. I have one ruleset for entire solution and this ruleset file is referenced in each project.

I would be useful to disable an analyzer on Visual Studio level or on solution level. But this feature should be done by Visual Studio team in Microsoft.

Because if I would implement a feature that can totally disable some analyzer, that analyzer could still be displayed as enabled in Visual Studio analyzers settings and that could be very confusing to the user.

**Comment by huoyaoyuan** [comment]
I can understand what you mean. But I want to change the default warning level, not disable it. For example, `RCS1025` is default a `Warning`, but `RCS1026` to `RCS1028` is `None`. That confuses me. In my opinion, the ones follow these rules can treat them as `Information`, and who don't follow these rules can treat them as `Hidden`.

**Comment by JosefPihrt** [comment]
#14

**Comment by JosefPihrt** [comment]
Leave a comment
